idf_component_register(
    REQUIRES
        esp_wifi
        esp_event
        nvs_flash
        esp_netif
        esp_timer
        driver
        lwip
        esp_http_server
        log
        freertos
        app_update
    PRIV_REQUIRES
        esp_app_format
    INCLUDE_DIRS
        "inc"
    SRCS
        "src/main.c"
        "src/config_manager.c"
        "src/wifi_manager.c"
        "src/time_manager.c"
        "src/pulse_input.c"
        "src/time_counter.c"
        "src/session_tracker.c"
        "src/session_log.c"
        "src/http_server.c"
        "src/http_server_utils.c"
        "src/http_server_config.c"
        "src/http_server_api.c"
        "src/http_server_export.c"
        "src/http_server_dashboard.c"
        "src/device_registry.c"
        "src/buzzer.c"
        "src/ota_manager.c"
        "src/http_server_ota.c"
        "src/button_reset.c"
)

target_compile_options(${COMPONENT_LIB} PRIVATE -Werror)
